POST http://0.0.0.0:5000/api/users/signup HTTP/1.1
content-type: application/json


{
    "email":"hello5@gmail.com",
    "password":"00000",
    "confirm-password":"00000",
    "name":"Tes5 User",
    "phone":"01025381934"
}

