PATCH  http://0.0.0.0:5000/api/users/updatePassword HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3MWNmYzFlMjhiMmU4NzdhZjhlZmVlZSIsImlhdCI6MTcyOTk1Mjg2NSwiZXhwIjoxNzMwMjEyMDY1fQ.SWiBDE7RsHHGfkVmcL6k0btbcN9iIBojNFLVz1F3eVA

{
    "passwordCurrent":"124",
    "password":"1234",
    "passwordConfirm":"1234"
}