POST  http://0.0.0.0:5000/api/products/ HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2ZTZlZWE4Y2MyNDc3ZjU1ZTUzMDJjNiIsImlhdCI6MTcyOTk2MjU0MSwiZXhwIjoxNzMwMjIxNzQxfQ.QlwVNQJDkjHYBiIzWDKPUq5V35KP3E-4O6GJob6wSps

{
        "name": "new product",
        "description": "new product with great features",
        "category": "phones",
        "price": 1123
}