POST http://0.0.0.0:5000/api/users/ HTTP/1.1
content-type: application/json

{
    "email":"test_user@gmail.com",
    "password":"00000",
    "confirm-password":"00000",
    "name":"Test User",
    "phone":"01025381934",
    "isAdmin":false

}

