PATCH  http://0.0.0.0:5000/api/users/6715450a878fa150d0b4662e HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3MGUzOWMyYmY4OTNlNDljMTVmOGQxMiIsImlhdCI6MTcyOTQ0NzE2MiwiZXhwIjoxNzMyMDM5MTYyfQ.lwevTqrT11PFVsqQyWhnn-pp4VomLKNz4rOt4OAsnk4

{
    "email":"test_user_updated@gmail.com",
    "password":"00000",
    "confirm-password":"00000",
    "name":"Test User",
    "phone":"01000000000"
}
